# GENERATE TIME: Sun Nov 10 18:17:22 2024
# CMD:
# /code/UHD-allinone/basicsr/train.py -opt /code/UHD-allinone/options/all-in-one/4dre/dwt_aio28_ft2.yml

# GENERATE TIME: Sat Sep 14 17:03:39 2024
# CMD:
# /code/UHD-allinone/basicsr/train.py -opt /code/UHD-allinone/options/all-in-one/dwt_kl8_fft.yml


# general settings
# name: debug
name: dwt_aio28_blk3|3_7_ft1lr4ft2lr2
model_type: FeMaSRModel
scale: &upscale 1
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: General_Image_Train
    type: mutiPairedcropImageDataset
    data_file_dir: /code/UHD-allinone/data_list/
    io_backend:
      type: disk
    de_type: ['denoise_15','denoise_25','denoise_50', 'dehaze', 'deblur', 'enhance']
    de_type_scale: [1,1,1,3,3,3]
    denoise_dir: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_noise/tarin_crop/
    bulr_dir: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_deblur/train/train_crop/
    enhance_dir: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_LL/train_crop/
    dehaze_dir: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_haze/train/train_crop/
    derain_dir: data/Train/Derain/
    gt_size: 1024
    use_resize_crop: False
    use_flip: False
    use_rot: False

    # data loader
    use_shuffle: true
    geometric_augs: True
    batch_size_per_gpu: &bsz 1
    num_worker_per_gpu: *bsz
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: *bsz

  val:
    name: LL
    type: PairedImageDataset
    dataroot_gt: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_LL/testing_crop_set/gt
    dataroot_lq: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_LL/testing_crop_set/input
    gt_size: 0
    io_backend:
      type: disk
    geometric_augs: True
    use_resize_crop: False
    use_flip: False
    use_rot: False
  
  val_2:
    name: bulr
    type: PairedImageDataset
    dataroot_gt: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_deblur/test/test_crop/gt
    dataroot_lq: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_deblur/test/test_crop/input
    gt_size: 0
    io_backend:
      type: disk
    geometric_augs: True
    use_resize_crop: False
    use_flip: False
    use_rot: False

  val_3:
    name: hazy
    type: PairedImageDataset
    dataroot_gt: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_haze/test/test_crop/gt
    dataroot_lq: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_haze/test/test_crop/input
    gt_size: 0
    io_backend:
      type: disk
    geometric_augs: True
    use_resize_crop: False
    use_flip: False
    use_rot: False

  val_4:
    name: denoise_50
    type: SingleImageDataset
    dataroot_lq: /data/liuyidi/nitre_2023_dehaze/data_dehaze/UHD_noise/test_crop/
    meta_info_file: /code/UHD-allinone/data_list/noisy/noise_samval.txt
    gt_size: 0
    deg: 50
    io_backend:
      type: disk
    geometric_augs: True
    use_resize_crop: False
    use_flip: False
    use_rot: False
# network structures
network_g:
  type: dwt_aio28

#  channel_query_dict: {8: 256, 16: 256, 32: 256, 64: 128, 128: 64, 256: 32, 512: 32,}
  dim: 16
  # mid_dim: 36
  dwt_dim: 3
  deg_num: 6
  n_blocks: [8,6,4,2]
  rank: [8,6,4]
  rank_scale : [0.3,0.4,1,0.8,1,1.2]
  ffn_scale: 2.0
  upscaling_factor: 4
  num_heads: 3
  vae_weight: /model/liuyidi/VAE/UHD-allinone/experiments/VAE|4deg*8_ft2(2)/models/net_g_latest.pth
  cls_weight: /model/liuyidi/VAE/UHD-allinone/experiments/Cls_deg4_50k*8/models/net_g_latest.pth
  prompt_scale: 4
  config: /model/liuyidi/VAE/UHD-allinone/experiments/VAE|4deg*8_ft2(2)/VAE4dm_ft2.yml
  # vae_weight: /data/liuyidi/nitre_2023_dehaze/data_dehaze/uhdformer/experiments/120kema_resfour/models/net_g_latest.pth
  # config: /data/liuyidi/nitre_2023_dehaze/data_dehaze/uhdformer/experiments/120kema_resfour/8_16_res.yml
  sample: True
  # vae_weight: ~

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  

# path
path:
  pretrain_network_hq: ~
  # pretrain_network_g: /model/liuyidi/VAE/UHD-allinone/experiments/fgt2_3m/models/net_g_latest.pth
  pretrain_network_g: ~
  pretrain_network_d: ~
  # pretrain_network_d: /model/liuyidi/VAE/UHD-allinone/experiments/fgt2_1/models/net_g_latest.pth
  strict_load: false
#  resume_state: /data_8T1/wangcong/AAAI24/521-UHDformerDehaze/experiments/014_FeMaSR_LQ_stage/training_states/390000.state
  resume_state: ~ 


# training settings
train:
  # ema_decay: 0.9
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-3
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [1000, 60000]
    restart_weights: [1, 1]
    eta_mins: [0.0002, 0.0000001]

  total_iter: 61000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0 
    reduction: mean
  pixel_ssim_opt:
    loss_weight: !!float 0.25

  fft_opt:
    type: FFTLoss
    loss_weight: !!float 0.1


  perceptual_opt:
    type: LPIPSLoss
    loss_weight: !!float 0
    
  gan_opt:
    type: GANLoss
    gan_type: hinge
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: 0

  codebook_opt:
    loss_weight: 0
  
  semantic_opt:
    loss_weight: 0

  net_d_iters: 0
  net_d_init_iters: !!float 0 

# validation settings·
val:
  val_freq: !!float 9e3
  # val_freq: !!float 10
  save_img: False

  key_metric: ssim
  metrics:
    psnr: # metric name, can be arbitrary
      type: psnr 
      crop_border: 4
      test_y_channel: true
    ssim:
      type: ssim 
      crop_border: 4
      test_y_channel: true
    # lpips:
    #   type: lpips 
    #   better: lower

# logging settings
logger:
  print_freq: 100
  # print_freq: 1
  save_checkpoint_freq: !!float 1e9
  save_latest_freq: !!float 9000
  show_tf_imgs_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: UHD-allinone
    resume_id: ~
    # resume_id: qk9g96p9
    # 2510322508-/UHD-allinone/qk9g96p9
# wandb:
    # project: ESRGAN
    # resume_id: ~

dist_params:
  backend: nccl
  port: 16500 #29500
find_unused_parameters: true
